spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}
  management:
    endpoints:
      web:
        exposure:
          include: health, info, metrics, prometheus
  config:
    import: application-security.yml


